services: docker
language: bash
addons:
  apt:
    packages:
      - python-pip

env:
  global:
    - PACKAGE_NAME=neonavigation_msgs
  matrix:
    - ROS_DISTRO_TARGET=kinetic
    - ROS_DISTRO_TARGET=melodic
branches:
  only:
    - master

before_install:
  - pip install --user gh-pr-comment

install: true

script:
  - docker build
    -t neonavigation-msgs
    -f .travis/Dockerfile
    --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET}
    --pull=true ${TRAVIS_BUILD_DIR}
    || (gh-pr-comment "[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_REPO_SLUG
    -e TRAVIS_BOT_GITHUB_TOKEN
    -e GITHUB_API_URL_BASE
    -e TRAVIS_BUILD_NUMBER
    -e TRAVIS_BUILD_WEB_URL
    neonavigation-msgs /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh

jobs:
  include:
    - stage: test
      env:
        - ROS_DISTRO_TARGET=noetic
      script:
        - BUILD_LINK="[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})]"
        - |
          docker run -it --rm \
            -v $(pwd):/src:ro \
            alpineros/ros-abuild:3.11-noetic \
            && gh-pr-comment "${BUILD_LINK} PASSED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS" \
            || (gh-pr-comment "${BUILD_LINK} FAILED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS"; false) \
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=kinetic COVERAGE_TEST=false
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=melodic COVERAGE_TEST=false
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=noetic COVERAGE_TEST=false
      before_install: pip install --user gh-pr-comment
      script: .travis/prerelease_test.sh
